### ISSUE TITLE
bibtex添加文獻錯誤

### ISSUE THREAD

**Issue by meflyup** [csxiaoyaojianxian/notehelper#1]
![image](https://user-images.githubusercontent.com/1710178/27132719-7aba00f8-5142-11e7-880e-140d73532b12.png)

> 批量模式同樣顯示此錯誤

**Comment by csxiaoyaojianxian** [comment]
@Junker4000

**Comment by Junker4000** [comment]
由于标准Bibtex中多个作者之间采用and而不是英文逗号分隔，因而在遇上用逗号分隔作者时解析会出现错误。
目前正在尝试编写另外一种思路的解析器，在新解析器完成之前可能没法解决这个问题
