### ISSUE TITLE
页面转移

### ISSUE THREAD

**Issue by meflyup** [csxiaoyaojianxian/notehelper#10]
当不在此页时，如果页面中有当前文章连接出现，就转移到此页。
![image](https://user-images.githubusercontent.com/1710178/27135854-3d5e6230-514c-11e7-9fcf-786e33539d54.png)

**Comment by csxiaoyaojianxian** [comment]
还没有理解具体的意思哦~~~

**Comment by keenezhu** [comment]
指点击keene就导航到文献keene详情页面（即图中的页面）

**Comment by csxiaoyaojianxian** [comment]
已经修改
