### ISSUE TITLE
pdf预览full width

### ISSUE THREAD

**Issue by meflyup** [csxiaoyaojianxian/notehelper#14]
pdf和右侧添加评注之间可否用一个活动的splitter分割，或者那种三角收缩箭头，让用户可以把pdf预览放大到占据全部宽度，不阅读时也可以收回来？

![image](https://user-images.githubusercontent.com/1710178/27261012-f0dcea3e-546c-11e7-8484-a1f115c915ff.png)

**Comment by csxiaoyaojianxian** [comment]
那这个地方这样吧，左侧的那个PDF显示按钮我这样处理：第一次点击，加载PDF并显示一半，第二次点击，全屏宽度，第三次点击，关闭显示，但是文件还在，只是不显示，后面再次点击只显示，不重新下载

**Comment by csxiaoyaojianxian** [comment]
已经修改
