### ISSUE TITLE
評論出現未知錯誤

### ISSUE THREAD

**Issue by meflyup** [csxiaoyaojianxian/notehelper#2]
![27132422-736656a4-5141-11e7-95d3-b35d137c83a5](https://user-images.githubusercontent.com/1710178/27134414-0f2839b2-5148-11e7-89b1-16b065c5f1d4.png)

**Comment by meflyup** [comment]
重复测试成功，我猜想是关键字分隔符的中英文后者半角全角造成的，建议用空格吧（可能英文不合适i）。或者其他不易出现混淆的方式。

**Comment by csxiaoyaojianxian** [comment]
@Junker4000

**Comment by Junker4000** [comment]
我们在测试的时候没有遇到过这种问题，可能是偶发现象，后续我们会再做测试，希望能提供一些您测试时的数据
