### ISSUE TITLE
pdf文件不显示

### ISSUE THREAD

**Issue by meflyup** [csxiaoyaojianxian/notehelper#5]
大概正在用哪个pdf.js+annotation是吧，目前不能文档。
![image](https://user-images.githubusercontent.com/1710178/27134390-fcdde8b0-5147-11e7-8df8-ba87adf475b7.png)

**Comment by csxiaoyaojianxian** [comment]
这个是因为之前使用的服务器路径取文件，现在改为传输文件流，前端的接收还有点问题，正在想办法解决

**Comment by csxiaoyaojianxian** [comment]
已经修复
