### ISSUE TITLE
希望修改一下导航逻辑

### ISSUE THREAD

**Issue by meflyup** [csxiaoyaojianxian/notehelper#7]
点击条目的时候  
![image](https://user-images.githubusercontent.com/1710178/27135047-202fe3ca-514a-11e7-811a-6b6450841e2e.png)  
去了这个：
![image](https://user-images.githubusercontent.com/1710178/27135080-33f1c1ee-514a-11e7-9c01-014d01ad2949.png)
更希望直接先转到已有评论页面：
![image](https://user-images.githubusercontent.com/1710178/27135104-4b7dda0a-514a-11e7-8467-a3980e1e3d1b.png)

**Comment by csxiaoyaojianxian** [comment]
好的，改

**Comment by keenezhu** [comment]
指在首页中，当点击了文献列表中的某一个文献，如果有评论，直接跳转到评论页，如果无评阅再跳转到详情页

**Comment by csxiaoyaojianxian** [comment]
已经修改，目前的逻辑是：点击缩略图跳转详情页，点击除缩略图外的区域，如果有评论跳转评论页，没有评论则跳转详情页
