### ISSUE TITLE
进入到已评论页面的时候，希望：

### ISSUE THREAD

**Issue by meflyup** [csxiaoyaojianxian/notehelper#8]
进入到已评论页面后这样的
![image](https://user-images.githubusercontent.com/1710178/27135194-7f967ff4-514a-11e7-8b83-2ce181ff0c4f.png)
如果5星没有内容，出一看就没有条目，这很容易造成   [此条issue类似的误解](https://github.com/csxiaoyaojianxian/notehelper/issues/3) 中的情况。故希望直接把tab设置到从5-1星中第一个有条目的。类似：
![image](https://user-images.githubusercontent.com/1710178/27135181-7311d8dc-514a-11e7-94bf-8bbb6950a1c2.png)

**Comment by csxiaoyaojianxian** [comment]
好的，改

**Comment by csxiaoyaojianxian** [comment]
已经修改
